[theme] # You have to add this line

primaryColor = '#FF8C02' # Bright Orange

backgroundColor = '#00325B' # Dark Blue

secondaryBackgroundColor = '#AA336A' # Lighter Blue

textColor = '#FFFFFF' # White

secondaryTextColor = '#FFFFFF' # White  
